package TasteProfile;


/**
* TasteProfile/ProfilerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Sunday, September 15, 2019 6:59:11 PM CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
public interface ProfilerOperations 
{

  /* Returns how many times a given song was played by all the users*/
  int getTimesPlayed (String song_id);

  /*												*/
  TasteProfile.UserProfile getUserProfile (String user_id);

  /* Returns how many times a given song was played by a given user*/
  int getTimesPlayedByUser (String user_id, String song_id);

  /* Returns the top three users played a given song */
  int getTopThreeUsersBySong (String song_id);

  /* Returns the top three songs played  by the given user */
  int getTopThreeSongsByUser (String song_id);
} // interface ProfilerOperations
